# Abstract
Test document for using aprof within markdown files.


# Introduction
Aprof should become aware of whether is is running within a sweave or markdown environment. This document tests this. 


# Code

Some typical aprof code;
```{make}
      render_markdown( strict = T )
  # create function to profile
          foo <- function(N){
                  preallocate<-numeric(N)
                  grow<-NULL
                   for(i in 1:N){
                       preallocate[i]<-N/(i+1)
                       grow<-c(grow,N/(i+1))
                      }
          }
     
          #save function to a source file and reload
          dump("foo",file="foo.R")

```


```{r aprof, echo=TRUE, engine='Rscript'}
         library(aprof,lib='~/R/lib')
     
          source("foo.R")

          # Profile the function
          Rprof("foo.out",line.profiling=TRUE)
          foo(3e4)
	  Rprof(append=FALSE)

          # Create a aprof object
          fooaprof<-aprof("foo.R","foo.out")
	  saveRDS(fooaprof,"./fooaprof.rds")
 ```



```{r makeplots, echo=TRUE}
          library(aprof,lib='~/R/lib')
          # Create a aprof object
          fooaprof<-readRDS("./fooaprof.rds")
          #display basic information, summarize and plot the object
          fooaprof
          summary(fooaprof)
          plot(fooaprof)


```

Profr

```{r profr}
library(profr,lib='~/R/lib')
  source("foo.R")
quantile_ex <- profr(
{foo(3e4)}, 0.01)
quantile_ex
```
